name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # run_style_check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - uses: conda-incubator/setup-miniconda@v2
  #       with:
  #         activate-environment: swe4s
  #         environment-file: environment.yaml
  #     - run: pylint $(git ls-files "*.py")
  run_pytest:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: swe4s
          environment-file: environment.yaml
      - name: Conda info
        shell: bash -el {0}
        run: |
          conda info
          conda list
      # - name: Conda list
      #   shell: pwsh
      #   run: conda list
      - name: Run pytest
        shell: bash -el {0}
        run: pytest
