name: Pylint and pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_pylint:
    name: Run pyint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: swe4s
          environment-file: environment.yaml
      - name: Run pylint
        run: pylint $(git ls-files "*.py")

  run_pytest:
    name: Run pytest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: swe4s
          environment-file: environment.yaml
      - name: Conda info
        run: |
          conda info
          conda list
      - name: Run pytest
        run: pytest
